apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: example
  labels:
    app: php
  annotations:
    secret.reloader.stakater.com/reload: 'example-secret'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: php:7.4.24-fpm
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: example-secret
                  key: api_key
