apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: example
spec:
  containers:
    - name: app
      image: php:7.4.24-fpm
      env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: example-secret
              key: api_key
  restartPolicy: Never
