apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: externalsecret-example
  namespace: example
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-example
    kind: SecretStore
  target:
    name: example-secret
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: example
        property: api_key
