apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-${namespace}
  namespace: ${namespace}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${aws_region}
      auth:
        jwt:
          serviceAccountRef:
            name: ${service_account_name}
